apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: ghcr.io/tbthomas56/hello-argo:0.0.1
        resources:
          limits:
            cpu: 1
            memory: 300M
        ports:
        - containerPort: {{ .Values.port}}
