apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP
