{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
spec:
  project: iza78587
  source:
    repoURL: {{ .repoURL }}
    path: {{ .path }}
    targetRevision: {{ .targetRevision }}
  destination:
    name: argus
    namespace: iza78587
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}

